{{- if and (or .Values.deployment .Values.job) .Values.envSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.envSecretName" . }}
  {{- if or .Values.annotations .Values.secret.annotations }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.secret.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    {{- with .Values.secret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  {{- range $name, $value := .Values.envSecret }}
  {{- $_ := required (printf "%s value required" $name) $value }}
  {{ $name }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}

{{- if .Values.volumesSecret.enable }}
{{- range .Values.volumesSecret.volumes }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.name" $ }}-file-{{ .name }}-secret
  {{- if or $.Values.annotations $.Values.secret.annotations }}
  annotations:
    {{- with $.Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with $.Values.secret.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
    {{- with $.Values.secret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: {{ .type | default "Opaque" }}
data:
  {{- range .files }}
  {{ .name }}: |2
    {{- .data | b64enc | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
