{{- if or .Values.deployment .Values.job }}
{{- if .Values.job }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.name" . }}-{{ randAlphaNum 5 | lower }}
{{- else }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" . }}
{{- end }}
  {{- if or .Values.annotations .Values.workload.annotations }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.workload.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    {{- with .Values.workload.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.job }}
  {{- with .Values.jobLimits }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- else }}
  replicas: {{ .Values.replicaCount }}
  {{- with .Values.strategy }}
  strategy:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  {{- end }}
  template:
    metadata:
      {{- if or .Values.annotations .Values.podAnnotations .Values.volumesConfigMap.enable .Values.envSecret }}
      annotations:
        {{- with .Values.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.volumesConfigMap.enable }}
        checksum/configmap: {{ include (print .Template.BasePath "/config-map.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.envSecret }}
        checksum/secret: {{ include (print .Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "app.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.job }}
      restartPolicy: {{ .Values.restartPolicy }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if ne .Values.automountServiceAccountToken "" }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dnsPolicy }}
      dnsPolicy: {{ . }}
      {{- end }}
      {{- with .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if ne .Values.hostIPC "" }}
      hostIPC: {{ .Values.hostIPC }}
      {{- end }}
      {{- with .Values.hostname }}
      hostname: {{ . }}
      {{- end }}
      {{- with .Values.hostnameOverride }}
      hostnameOverride: {{ . }}
      {{- end }}
      {{- if ne .Values.hostNetwork "" }}
      hostNetwork: {{ .Values.hostNetwork }}
      {{- end }}
      {{- if ne .Values.hostPID "" }}
      hostPID: {{ .Values.hostPID }}
      {{- end }}
      {{- if ne .Values.hostUsers "" }}
      hostUsers: {{ .Values.hostUsers }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.resourceClaims }}
      resourceClaims:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.runtimeClassName }}
      runtimeClassName: {{ . }}
      {{- end }}
      {{- if ne .Values.terminationGracePeriodSeconds "" }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- include "initContainers.sorted" $ | nindent 8 }}
      {{- end }}
      containers:
        {{- if .Values.jaegerAgent.enabled }}
        - name: jaeger-agent
          image: "jaegertracing/jaeger-agent:{{ .Values.jaegerAgent.version }}"
          {{- include "container.imagePullPolicy" .Values.jaegerAgent | nindent 10 -}}
          {{- include "container.ports" .Values.jaegerAgent | nindent 10 -}}
          args:
            - --reporter.grpc.host-port=dns:///jaeger-collector-headless.{{ .Values.jaegerAgent.namespace }}:14250
            - --reporter.type=grpc
        {{- end }}
        - name: {{ include "app.name" . }}
          {{- $containerType := "appContainer" }}
          {{- include "container.spec" (list $ .Values $containerType) | nindent 10 -}}
      {{- if include "volumes.spec" $ }}
      volumes:
        {{- include "volumes.spec" $ | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
